# configure updates globally, default is all
update: all # allowed [all, insecure, False]

# configure dependency pinning globally, default is True
pin: True # allowed [True, False]

# set the default branch, default is the default branch on GitHub
branch: develop

# update schedule, default is not set
# the bot will visit the repo once and bundle all updates in a single PR for the given
# day/week/month
schedule: "every day" # allowed ["every day", "every week", "every two weeks", "every month"]

# configure requirement files search, default is True
# the bot will search for files ending with .txt/.pip with a requirements in their file paths
search: False # allowed [True, False]

# adding requirements files manually, default is empty
requirements:
  - requirements.txt
      # update all dependencies and pin them
      updates: all
      pin: True

# add a label to pull requests, default is not set
# requires private repo permissions, even on public repos
label_prs: update

# assign users to pull requests, default is not set
# requires private repo permissions, even on public repos
assignees:
 - carl
 - carlsen

# configure the branch prefix the bot is using, default is pyup-
branch_prefix: pyup/

# set a global prefix for PRs, default is empty
pr_prefix: "Bug #12345"

# allow to close stale PRs, default is True
close_prs: True